# Generated by Django 5.2.12 on 2026-03-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField()),
                ('traceback', models.TextField()),
                ('component', models.CharField(max_length=100)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(choices=[('NIFTY50', 'Nifty 50'), ('BANKNIFTY', 'Bank Nifty'), ('BANKEX', 'Bankex'), ('SENSEX', 'Sensex'), ('MIDCAPNIFTY', 'Midcap Nifty'), ('FINNIFTY', 'Finnifty')], max_length=50)),
                ('side', models.CharField(choices=[('CALL', 'CALL'), ('PUT', 'PUT')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stoploss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
