# Generated by Django 5.2.12 on 2026-03-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradealert',
            name='accuracy',
            field=models.CharField(default='94%', max_length=20),
        ),
        migrations.AddField(
            model_name='tradealert',
            name='contract',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tradealert',
            name='expiry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tradealert',
            name='premium_decay',
            field=models.CharField(default='Low', max_length=20),
        ),
        migrations.AddField(
            model_name='tradealert',
            name='premium_ltp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tradealert',
            name='spot_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tradealert',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
