# Generated by Django 5.2.12 on 2026-03-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_tradealert_accuracy_tradealert_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradealert',
            name='gamma_velocity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tradealert',
            name='imi_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradealert',
            name='oi_momentum_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
