# Generated by Django 5.2.12 on 2026-03-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_tradealert_gamma_velocity_tradealert_imi_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradealert',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradealert',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradealert',
            name='sl_hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradealert',
            name='t1_hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradealert',
            name='t2_hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradealert',
            name='t3_hit',
            field=models.BooleanField(default=False),
        ),
    ]
