# Generated by Django 5.2.12 on 2026-03-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_securitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=50, unique=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Healthy', max_length=20)),
                ('error_count', models.IntegerField(default=0)),
            ],
        ),
    ]
